
### Places API 검색 테스트
POST https://places.googleapis.com/v1/places:searchText
Content-Type: application/json
X-Goog-Api-Key: -
X-Goog-FieldMask:places.displayName,places.businessStatus
Referer: http://localhost:3000

{
  "textQuery": "로프트",
  # "locationBias": {
  #   "circle": {
  #     "center": {
  #       "latitude": 34.7024,
  #       "longitude": 135.4959
  #     },
  #     "radius": 10000.0
  #   }
  # }
}

### Places Detail 검색 테스트 
POST https://places.googleapis.com/v1/places/ChIJHZ9qxhDnAGARS3udWVQdvD0
Content-Type: application/json
X-Goog-Api-Key: -
X-Goog-FieldMask:formattedAddress
Referer: http://localhost:3000

### route
POST https://routes.googleapis.com/directions/v2:computeRoutes
Content-Type: application/json
X-Goog-Api-Key:-
X-Goog-FieldMask:routes.legs.duration,routes.legs.distanceMeters
Referer: http://localhost:3000

{
  "origin": {
    "location": {
      "latLng": {
        "latitude": 37.544364,
        "longitude": 127.052674
      }
    }
  },
  "destination": {
    "location": {
      "latLng": {
        "latitude": 37.544632,
        "longitude": 126.987684
      }
    }
  },
  "travelMode": "WALK",
}

###

POST https://routes.googleapis.com/directions/v2:computeRoutes
Content-Type: application/json
X-Goog-Api-Key: AIzaSyAljCs6vW7Yj3rl2icxgHkTiZyAM3bJp4Q
X-Goog-FieldMask: routes.duration,routes.distanceMeters
Referer: http://localhost:3000

{
  "origin": {
    "placeId": "ChIJ577hF1elfDURkCAprPDPpHQ"
  },
  "destination": {
    "placeId": "ChIJZXyrwjeifDUR95WK4e_vnws"
  },
  "travelMode": "BICYCLE"
}