@apiKey = -

### Places API 검색 테스트
POST https://places.googleapis.com/v1/places:searchText
Content-Type: application/json
X-Goog-Api-Key: -
X-Goog-FieldMask:places.displayName,places.businessStatus
Referer: http://localhost:3000

{
  "textQuery": "로프트",
  # "locationBias": {
  #   "circle": {
  #     "center": {
  #       "latitude": 34.7024,
  #       "longitude": 135.4959
  #     },
  #     "radius": 10000.0
  #   }
  # }
}

### Places Detail 검색 테스트 
POST https://places.googleapis.com/v1/places/ChIJHZ9qxhDnAGARS3udWVQdvD0
Content-Type: application/json
X-Goog-Api-Key: -
X-Goog-FieldMask:formattedAddress
Referer: http://localhost:3000
