export const COUNTRIES = [
  {
    label: '한국',
    languageCode: 'ko',
    countryCode: 'KOR',
    latitude: 37.5556,
    longitude: 126.9915,
    currencyCode: 'WON',
  },
  { label: '가나', languageCode: 'en', countryCode: 'GHA', latitude: 7.9465, longitude: -1.0232, currencyCode: 'GHS' },
  { label: '가봉', languageCode: 'fr', countryCode: 'GAB', latitude: -0.8037, longitude: 11.6094, currencyCode: 'XAF' },
  {
    label: '가이아나공화국',
    languageCode: 'en',
    countryCode: 'GUY',
    latitude: 4.8604,
    longitude: -58.9302,
    currencyCode: 'GYD',
  },
  {
    label: '감비아',
    languageCode: 'en',
    countryCode: 'GMB',
    latitude: 13.4432,
    longitude: -15.3101,
    currencyCode: 'GMD',
  },
  {
    label: '과테말라',
    languageCode: 'es',
    countryCode: 'GTM',
    latitude: 15.7835,
    longitude: -90.2308,
    currencyCode: 'GTQ',
  },
  {
    label: '그레나다',
    languageCode: 'en',
    countryCode: 'GRD',
    latitude: 12.1165,
    longitude: -61.679,
    currencyCode: 'XCD',
  },
  {
    label: '그리스',
    languageCode: 'el',
    countryCode: 'GRC',
    latitude: 39.0742,
    longitude: 21.8243,
    currencyCode: 'EUR',
  },
  { label: '기니', languageCode: 'fr', countryCode: 'GIN', latitude: 9.9456, longitude: -11.3247, currencyCode: 'GNF' },
  {
    label: '기니비사우',
    languageCode: 'pt',
    countryCode: 'GNB',
    latitude: 11.8037,
    longitude: -15.1804,
    currencyCode: 'XOF',
  },
  {
    label: '나미비아',
    languageCode: 'en',
    countryCode: 'NAM',
    latitude: -22.9576,
    longitude: 18.4904,
    currencyCode: 'NAD',
  },
  {
    label: '나우루',
    languageCode: 'en',
    countryCode: 'NRU',
    latitude: -0.5228,
    longitude: 166.9315,
    currencyCode: 'AUD',
  },
  {
    label: '나이지리아',
    languageCode: 'en',
    countryCode: 'NGA',
    latitude: 9.082,
    longitude: 8.6753,
    currencyCode: 'NGN',
  },
  { label: '남수단', languageCode: 'en', countryCode: 'SSD', latitude: 6.877, longitude: 31.307, currencyCode: 'SSP' },
  {
    label: '남아프리카공화국',
    languageCode: 'en',
    countryCode: 'ZAF',
    latitude: -30.5595,
    longitude: 22.9375,
    currencyCode: 'ZAR',
  },
  {
    label: '네덜란드',
    languageCode: 'nl',
    countryCode: 'NLD',
    latitude: 52.1326,
    longitude: 5.2913,
    currencyCode: 'EUR',
  },
  { label: '네팔', languageCode: 'ne', countryCode: 'NPL', latitude: 28.3949, longitude: 84.124, currencyCode: 'NPR' },
  {
    label: '노르웨이',
    languageCode: 'no',
    countryCode: 'NOR',
    latitude: 60.472,
    longitude: 8.4689,
    currencyCode: 'NOK',
  },
  {
    label: '뉴질랜드',
    languageCode: 'en',
    countryCode: 'NZL',
    latitude: -40.9006,
    longitude: 174.886,
    currencyCode: 'NZD',
  },
  {
    label: '니우에',
    languageCode: 'en',
    countryCode: 'NIU',
    latitude: -19.0544,
    longitude: -169.8672,
    currencyCode: 'NZD',
  },
  {
    label: '니제르',
    languageCode: 'fr',
    countryCode: 'NER',
    latitude: 17.6078,
    longitude: 8.0817,
    currencyCode: 'XOF',
  },
  {
    label: '니카라과',
    languageCode: 'es',
    countryCode: 'NIC',
    latitude: 12.8654,
    longitude: -85.2072,
    currencyCode: 'NIO',
  },
  {
    label: '대만',
    languageCode: 'zh-TW',
    countryCode: 'TWN',
    latitude: 23.6978,
    longitude: 120.9605,
    currencyCode: 'TWD',
  },
  {
    label: '덴마크',
    languageCode: 'da',
    countryCode: 'DNK',
    latitude: 56.2639,
    longitude: 9.5018,
    currencyCode: 'DKK',
  },
  {
    label: '도미니카공화국',
    languageCode: 'es',
    countryCode: 'DOM',
    latitude: 18.7357,
    longitude: -70.1627,
    currencyCode: 'DOP',
  },
  {
    label: '도미니카연방',
    languageCode: 'en',
    countryCode: 'DMA',
    latitude: 15.415,
    longitude: -61.371,
    currencyCode: 'XCD',
  },
  { label: '독일', languageCode: 'de', countryCode: 'DEU', latitude: 51.1657, longitude: 10.4515, currencyCode: 'EUR' },
  {
    label: '동티모르',
    languageCode: 'pt',
    countryCode: 'TLS',
    latitude: -8.8742,
    longitude: 125.7275,
    currencyCode: 'USD',
  },
  {
    label: '라오스',
    languageCode: 'lo',
    countryCode: 'LAO',
    latitude: 19.8563,
    longitude: 102.4955,
    currencyCode: 'LAK',
  },
  {
    label: '라이베리아',
    languageCode: 'en',
    countryCode: 'LBR',
    latitude: 6.4281,
    longitude: -9.4295,
    currencyCode: 'LRD',
  },
  {
    label: '라트비아',
    languageCode: 'lv',
    countryCode: 'LVA',
    latitude: 56.8796,
    longitude: 24.6032,
    currencyCode: 'EUR',
  },
  {
    label: '러시아',
    languageCode: 'ru',
    countryCode: 'RUS',
    latitude: 61.524,
    longitude: 105.3188,
    currencyCode: 'RUB',
  },
  {
    label: '레바논',
    languageCode: 'ar',
    countryCode: 'LBN',
    latitude: 33.8547,
    longitude: 35.8623,
    currencyCode: 'LBP',
  },
  {
    label: '레소토',
    languageCode: 'en',
    countryCode: 'LSO',
    latitude: -29.61,
    longitude: 28.2336,
    currencyCode: 'LSL',
  },
  {
    label: '루마니아',
    languageCode: 'ro',
    countryCode: 'ROU',
    latitude: 45.9432,
    longitude: 24.9668,
    currencyCode: 'RON',
  },
  {
    label: '룩셈부르크',
    languageCode: 'fr',
    countryCode: 'LUX',
    latitude: 49.8153,
    longitude: 6.1296,
    currencyCode: 'EUR',
  },
  {
    label: '르완다',
    languageCode: 'fr',
    countryCode: 'RWA',
    latitude: -1.9403,
    longitude: 29.8739,
    currencyCode: 'RWF',
  },
  {
    label: '리비아',
    languageCode: 'ar',
    countryCode: 'LBY',
    latitude: 26.3351,
    longitude: 17.2283,
    currencyCode: 'LYD',
  },
  {
    label: '리투아니아',
    languageCode: 'lt',
    countryCode: 'LTU',
    latitude: 55.1694,
    longitude: 23.8813,
    currencyCode: 'EUR',
  },
  {
    label: '리히텐슈타인',
    languageCode: 'de',
    countryCode: 'LIE',
    latitude: 47.166,
    longitude: 9.5554,
    currencyCode: 'CHF',
  },
  {
    label: '마다가스카르',
    languageCode: 'fr',
    countryCode: 'MDG',
    latitude: -18.7669,
    longitude: 46.8691,
    currencyCode: 'MGA',
  },
  {
    label: '마셜제도',
    languageCode: 'en',
    countryCode: 'MHL',
    latitude: 7.1315,
    longitude: 171.1845,
    currencyCode: 'USD',
  },
  {
    label: '마이크로네시아',
    languageCode: 'en',
    countryCode: 'FSM',
    latitude: 7.4256,
    longitude: 150.5508,
    currencyCode: 'USD',
  },
  {
    label: '마카오',
    languageCode: 'zh-HK',
    countryCode: 'MAC',
    latitude: 22.1987,
    longitude: 113.5439,
    currencyCode: 'MOP',
  },
  {
    label: '말라위',
    languageCode: 'en',
    countryCode: 'MWI',
    latitude: -13.2543,
    longitude: 34.3015,
    currencyCode: 'MWK',
  },
  {
    label: '말레이시아',
    languageCode: 'ms',
    countryCode: 'MYS',
    latitude: 4.2105,
    longitude: 101.9758,
    currencyCode: 'MYR',
  },
  { label: '말리', languageCode: 'fr', countryCode: 'MLI', latitude: 17.5707, longitude: -3.9962, currencyCode: 'XOF' },
  {
    label: '멕시코',
    languageCode: 'es',
    countryCode: 'MEX',
    latitude: 23.6345,
    longitude: -102.5528,
    currencyCode: 'MXN',
  },
  {
    label: '모나코',
    languageCode: 'fr',
    countryCode: 'MCO',
    latitude: 43.7384,
    longitude: 7.4246,
    currencyCode: 'EUR',
  },
  {
    label: '모로코',
    languageCode: 'ar',
    countryCode: 'MAR',
    latitude: 31.7917,
    longitude: -7.0926,
    currencyCode: 'MAD',
  },
  {
    label: '모리셔스',
    languageCode: 'fr',
    countryCode: 'MUS',
    latitude: -20.3484,
    longitude: 57.5522,
    currencyCode: 'MUR',
  },
  {
    label: '모리타니아',
    languageCode: 'ar',
    countryCode: 'MRT',
    latitude: 21.0079,
    longitude: -10.9408,
    currencyCode: 'MRU',
  },
  {
    label: '모잠비크',
    languageCode: 'pt',
    countryCode: 'MOZ',
    latitude: -18.6657,
    longitude: 35.5296,
    currencyCode: 'MZN',
  },
  {
    label: '몬테네그로',
    languageCode: 'sr',
    countryCode: 'MNE',
    latitude: 42.7087,
    longitude: 19.3744,
    currencyCode: 'EUR',
  },
  {
    label: '몰도바',
    languageCode: 'ro',
    countryCode: 'MDA',
    latitude: 47.4116,
    longitude: 28.3699,
    currencyCode: 'MDL',
  },
  {
    label: '몰디브',
    languageCode: 'en',
    countryCode: 'MDV',
    latitude: 3.2028,
    longitude: 73.2207,
    currencyCode: 'MVR',
  },
  { label: '몰타', languageCode: 'en', countryCode: 'MLT', latitude: 35.9375, longitude: 14.3754, currencyCode: 'EUR' },
  {
    label: '몽골',
    languageCode: 'mn',
    countryCode: 'MNG',
    latitude: 46.8625,
    longitude: 103.8467,
    currencyCode: 'MNT',
  },
  {
    label: '미국',
    languageCode: 'en',
    countryCode: 'USA',
    latitude: 37.0902,
    longitude: -95.7129,
    currencyCode: 'USD',
  },
  {
    label: '미얀마',
    languageCode: 'my',
    countryCode: 'MMR',
    latitude: 21.9162,
    longitude: 95.956,
    currencyCode: 'MMK',
  },
  {
    label: '바누아투',
    languageCode: 'fr',
    countryCode: 'VUT',
    latitude: -15.3767,
    longitude: 166.9592,
    currencyCode: 'VUV',
  },
  { label: '바레인', languageCode: 'ar', countryCode: 'BHR', latitude: 26.0275, longitude: 50.55, currencyCode: 'BHD' },
  {
    label: '바베이도스',
    languageCode: 'en',
    countryCode: 'BRB',
    latitude: 13.1939,
    longitude: -59.5432,
    currencyCode: 'BBD',
  },
  {
    label: '바하마',
    languageCode: 'en',
    countryCode: 'BHS',
    latitude: 25.0343,
    longitude: -77.3963,
    currencyCode: 'BSD',
  },
  {
    label: '방글라데시',
    languageCode: 'bn',
    countryCode: 'BGD',
    latitude: 23.685,
    longitude: 90.3563,
    currencyCode: 'BDT',
  },
  { label: '베냉', languageCode: 'fr', countryCode: 'BEN', latitude: 9.3077, longitude: 2.3158, currencyCode: 'XOF' },
  {
    label: '베네수엘라',
    languageCode: 'es',
    countryCode: 'VEN',
    latitude: 6.4238,
    longitude: -66.5897,
    currencyCode: 'VES',
  },
  {
    label: '베트남',
    languageCode: 'vi',
    countryCode: 'VNM',
    latitude: 14.0583,
    longitude: 108.2772,
    currencyCode: 'VND',
  },
  {
    label: '벨기에',
    languageCode: 'fr',
    countryCode: 'BEL',
    latitude: 50.5039,
    longitude: 4.4699,
    currencyCode: 'EUR',
  },
  {
    label: '벨라루스',
    languageCode: 'be',
    countryCode: 'BLR',
    latitude: 53.7098,
    longitude: 27.9534,
    currencyCode: 'BYN',
  },
  {
    label: '벨리즈',
    languageCode: 'en',
    countryCode: 'BLZ',
    latitude: 17.1899,
    longitude: -88.4976,
    currencyCode: 'BZD',
  },
  {
    label: '보스니아헤르체고비나',
    languageCode: 'bs',
    countryCode: 'BIH',
    latitude: 43.9159,
    longitude: 17.6791,
    currencyCode: 'BAM',
  },
  {
    label: '보츠와나',
    languageCode: 'en',
    countryCode: 'BWA',
    latitude: -22.3285,
    longitude: 24.6849,
    currencyCode: 'BWP',
  },
  {
    label: '볼리비아',
    languageCode: 'es',
    countryCode: 'BOL',
    latitude: -16.2902,
    longitude: -63.5887,
    currencyCode: 'BOB',
  },
  {
    label: '부룬디',
    languageCode: 'fr',
    countryCode: 'BDI',
    latitude: -3.3731,
    longitude: 29.9189,
    currencyCode: 'BIF',
  },
  {
    label: '부르키나파소',
    languageCode: 'fr',
    countryCode: 'BFA',
    latitude: 12.3641,
    longitude: -1.5339,
    currencyCode: 'XOF',
  },
  { label: '부탄', languageCode: 'en', countryCode: 'BTN', latitude: 27.5142, longitude: 90.4336, currencyCode: 'BTN' },
  {
    label: '북마케도니아',
    languageCode: 'mk',
    countryCode: 'MKD',
    latitude: 41.6086,
    longitude: 21.7453,
    currencyCode: 'MKD',
  },
  {
    label: '불가리아',
    languageCode: 'bg',
    countryCode: 'BGR',
    latitude: 42.7339,
    longitude: 25.4858,
    currencyCode: 'BGN',
  },
  {
    label: '브라질',
    languageCode: 'pt-BR',
    countryCode: 'BRA',
    latitude: -14.235,
    longitude: -51.9253,
    currencyCode: 'BRL',
  },
  {
    label: '브루나이',
    languageCode: 'ms',
    countryCode: 'BRN',
    latitude: 4.5353,
    longitude: 114.7277,
    currencyCode: 'BND',
  },
  {
    label: '사모아',
    languageCode: 'en',
    countryCode: 'WSM',
    latitude: -13.759,
    longitude: -172.1046,
    currencyCode: 'WST',
  },
  {
    label: '사우디아라비아',
    languageCode: 'ar',
    countryCode: 'SAU',
    latitude: 23.8859,
    longitude: 45.0792,
    currencyCode: 'SAR',
  },
  {
    label: '사이프러스',
    languageCode: 'el',
    countryCode: 'CYP',
    latitude: 35.1264,
    longitude: 33.4299,
    currencyCode: 'EUR',
  },
  {
    label: '산마리노',
    languageCode: 'it',
    countryCode: 'SMR',
    latitude: 43.9424,
    longitude: 12.4578,
    currencyCode: 'EUR',
  },
  {
    label: '상투메프린시페',
    languageCode: 'pt',
    countryCode: 'STP',
    latitude: 0.1864,
    longitude: 6.6131,
    currencyCode: 'STN',
  },
  {
    label: '세네갈',
    languageCode: 'fr',
    countryCode: 'SEN',
    latitude: 14.4974,
    longitude: -14.4524,
    currencyCode: 'XOF',
  },
  {
    label: '세르비아',
    languageCode: 'sr',
    countryCode: 'SRB',
    latitude: 44.0165,
    longitude: 21.0059,
    currencyCode: 'RSD',
  },
  {
    label: '세이셸',
    languageCode: 'fr',
    countryCode: 'SYC',
    latitude: -4.6796,
    longitude: 55.492,
    currencyCode: 'SCR',
  },
  {
    label: '세인트루시아',
    languageCode: 'en',
    countryCode: 'LCA',
    latitude: 13.9094,
    longitude: -60.9789,
    currencyCode: 'XCD',
  },
  {
    label: '세인트빈센트그레나딘',
    languageCode: 'en',
    countryCode: 'VCT',
    latitude: 12.9843,
    longitude: -61.2872,
    currencyCode: 'XCD',
  },
  {
    label: '세인트키츠네비스',
    languageCode: 'en',
    countryCode: 'KNA',
    latitude: 17.3578,
    longitude: -62.783,
    currencyCode: 'XCD',
  },
  {
    label: '소말리아',
    languageCode: 'ar',
    countryCode: 'SOM',
    latitude: 5.1521,
    longitude: 46.1996,
    currencyCode: 'SOS',
  },
  {
    label: '솔로몬제도',
    languageCode: 'en',
    countryCode: 'SLB',
    latitude: -9.6457,
    longitude: 160.1562,
    currencyCode: 'SBD',
  },
  { label: '수단', languageCode: 'ar', countryCode: 'SDN', latitude: 12.8628, longitude: 30.2176, currencyCode: 'SDG' },
  {
    label: '수리남',
    languageCode: 'nl',
    countryCode: 'SUR',
    latitude: 3.9193,
    longitude: -56.0278,
    currencyCode: 'SRD',
  },
  {
    label: '스리랑카',
    languageCode: 'si',
    countryCode: 'LKA',
    latitude: 7.8731,
    longitude: 80.7718,
    currencyCode: 'LKR',
  },
  {
    label: '스웨덴',
    languageCode: 'sv',
    countryCode: 'SWE',
    latitude: 60.1282,
    longitude: 18.6435,
    currencyCode: 'SEK',
  },
  {
    label: '스위스',
    languageCode: 'de',
    countryCode: 'CHE',
    latitude: 46.8182,
    longitude: 8.2275,
    currencyCode: 'CHF',
  },
  {
    label: '스페인',
    languageCode: 'es',
    countryCode: 'ESP',
    latitude: 40.4637,
    longitude: -3.7492,
    currencyCode: 'EUR',
  },
  {
    label: '슬로바키아',
    languageCode: 'sk',
    countryCode: 'SVK',
    latitude: 48.669,
    longitude: 19.699,
    currencyCode: 'EUR',
  },
  {
    label: '슬로베니아',
    languageCode: 'sl',
    countryCode: 'SVN',
    latitude: 46.1512,
    longitude: 14.9955,
    currencyCode: 'EUR',
  },
  {
    label: '시리아',
    languageCode: 'ar',
    countryCode: 'SYR',
    latitude: 34.8021,
    longitude: 38.9968,
    currencyCode: 'SYP',
  },
  {
    label: '시에라리온',
    languageCode: 'en',
    countryCode: 'SLE',
    latitude: 8.4606,
    longitude: -11.7799,
    currencyCode: 'SLL',
  },
  {
    label: '싱가포르',
    languageCode: 'en',
    countryCode: 'SGP',
    latitude: 1.3521,
    longitude: 103.8198,
    currencyCode: 'SGD',
  },
  {
    label: '아랍에미리트',
    languageCode: 'ar',
    countryCode: 'ARE',
    latitude: 23.4241,
    longitude: 53.8478,
    currencyCode: 'AED',
  },
  {
    label: '아르메니아',
    languageCode: 'hy',
    countryCode: 'ARM',
    latitude: 40.0691,
    longitude: 45.0382,
    currencyCode: 'AMD',
  },
  {
    label: '아르헨티나',
    languageCode: 'es',
    countryCode: 'ARG',
    latitude: -38.4161,
    longitude: -63.6167,
    currencyCode: 'ARS',
  },
  {
    label: '아이슬란드',
    languageCode: 'is',
    countryCode: 'ISL',
    latitude: 64.9631,
    longitude: -19.0208,
    currencyCode: 'ISK',
  },
  {
    label: '아이티',
    languageCode: 'fr',
    countryCode: 'HTI',
    latitude: 18.9712,
    longitude: -72.2852,
    currencyCode: 'HTG',
  },
  {
    label: '아일랜드',
    languageCode: 'en',
    countryCode: 'IRL',
    latitude: 53.1424,
    longitude: -7.6921,
    currencyCode: 'EUR',
  },
  {
    label: '아제르바이잔',
    languageCode: 'az',
    countryCode: 'AZE',
    latitude: 40.1431,
    longitude: 47.5769,
    currencyCode: 'AZN',
  },
  {
    label: '아프가니스탄',
    languageCode: 'fa',
    countryCode: 'AFG',
    latitude: 33.9391,
    longitude: 67.71,
    currencyCode: 'AFN',
  },
  {
    label: '안도라',
    languageCode: 'ca',
    countryCode: 'AND',
    latitude: 42.5063,
    longitude: 1.5218,
    currencyCode: 'EUR',
  },
  {
    label: '알바니아',
    languageCode: 'sq',
    countryCode: 'ALB',
    latitude: 41.1533,
    longitude: 20.1683,
    currencyCode: 'ALL',
  },
  {
    label: '알제리',
    languageCode: 'ar',
    countryCode: 'DZA',
    latitude: 28.0339,
    longitude: 1.6596,
    currencyCode: 'DZD',
  },
  {
    label: '앙골라',
    languageCode: 'pt',
    countryCode: 'AGO',
    latitude: -11.2027,
    longitude: 17.8739,
    currencyCode: 'AOA',
  },
  {
    label: '앤티가바부다',
    languageCode: 'en',
    countryCode: 'ATG',
    latitude: 17.0608,
    longitude: -61.7964,
    currencyCode: 'XCD',
  },
  {
    label: '에리트레아',
    languageCode: 'ar',
    countryCode: 'ERI',
    latitude: 15.1794,
    longitude: 39.7823,
    currencyCode: 'ERN',
  },
  {
    label: '에스와티니',
    languageCode: 'en',
    countryCode: 'SWZ',
    latitude: -26.5225,
    longitude: 31.4659,
    currencyCode: 'SZL',
  },
  {
    label: '에스토니아',
    languageCode: 'et',
    countryCode: 'EST',
    latitude: 58.5953,
    longitude: 25.0136,
    currencyCode: 'EUR',
  },
  {
    label: '에콰도르',
    languageCode: 'es',
    countryCode: 'ECU',
    latitude: -1.8312,
    longitude: -78.1834,
    currencyCode: 'USD',
  },
  {
    label: '에티오피아',
    languageCode: 'am',
    countryCode: 'ETH',
    latitude: 9.145,
    longitude: 40.4897,
    currencyCode: 'ETB',
  },
  {
    label: '엘살바도르',
    languageCode: 'es',
    countryCode: 'SLV',
    latitude: 13.7942,
    longitude: -88.8965,
    currencyCode: 'USD',
  },
  {
    label: '영국',
    languageCode: 'en-GB',
    countryCode: 'GBR',
    latitude: 55.3781,
    longitude: -3.436,
    currencyCode: 'GBP',
  },
  { label: '예멘', languageCode: 'ar', countryCode: 'YEM', latitude: 15.5527, longitude: 48.5164, currencyCode: 'YER' },
  { label: '오만', languageCode: 'ar', countryCode: 'OMN', latitude: 21.4735, longitude: 55.9754, currencyCode: 'OMR' },
  {
    label: '오스트리아',
    languageCode: 'de',
    countryCode: 'AUT',
    latitude: 47.5162,
    longitude: 14.5501,
    currencyCode: 'EUR',
  },
  {
    label: '온두라스',
    languageCode: 'es',
    countryCode: 'HND',
    latitude: 15.1999,
    longitude: -86.2419,
    currencyCode: 'HNL',
  },
  {
    label: '요르단',
    languageCode: 'ar',
    countryCode: 'JOR',
    latitude: 30.5852,
    longitude: 36.2384,
    currencyCode: 'JOD',
  },
  {
    label: '우간다',
    languageCode: 'en',
    countryCode: 'UGA',
    latitude: 1.3733,
    longitude: 32.2903,
    currencyCode: 'UGX',
  },
  {
    label: '우루과이',
    languageCode: 'es',
    countryCode: 'URY',
    latitude: -32.5228,
    longitude: -55.7658,
    currencyCode: 'UYU',
  },
  {
    label: '우즈베키스탄',
    languageCode: 'uz',
    countryCode: 'UZB',
    latitude: 41.3775,
    longitude: 64.5853,
    currencyCode: 'UZS',
  },
  {
    label: '우크라이나',
    languageCode: 'uk',
    countryCode: 'UKR',
    latitude: 48.3794,
    longitude: 31.1656,
    currencyCode: 'UAH',
  },
  {
    label: '이라크',
    languageCode: 'ar',
    countryCode: 'IRQ',
    latitude: 33.2232,
    longitude: 43.6793,
    currencyCode: 'IQD',
  },
  { label: '이란', languageCode: 'fa', countryCode: 'IRN', latitude: 32.4279, longitude: 53.688, currencyCode: 'IRR' },
  {
    label: '이스라엘',
    languageCode: 'he',
    countryCode: 'ISR',
    latitude: 31.0461,
    longitude: 34.8516,
    currencyCode: 'ILS',
  },
  {
    label: '이집트',
    languageCode: 'ar',
    countryCode: 'EGY',
    latitude: 26.8206,
    longitude: 30.8025,
    currencyCode: 'EGP',
  },
  {
    label: '이탈리아',
    languageCode: 'it',
    countryCode: 'ITA',
    latitude: 41.8719,
    longitude: 12.5674,
    currencyCode: 'EUR',
  },
  { label: '인도', languageCode: 'hi', countryCode: 'IND', latitude: 20.5937, longitude: 78.9629, currencyCode: 'INR' },
  {
    label: '인도네시아',
    languageCode: 'id',
    countryCode: 'IDN',
    latitude: -0.7893,
    longitude: 113.9213,
    currencyCode: 'IDR',
  },
  {
    label: '일본',
    languageCode: 'ja',
    countryCode: 'JPN',
    latitude: 36.2048,
    longitude: 138.2529,
    currencyCode: 'JPY',
  },
  {
    label: '자메이카',
    languageCode: 'en',
    countryCode: 'JAM',
    latitude: 18.1096,
    longitude: -77.2975,
    currencyCode: 'JMD',
  },
  {
    label: '잠비아',
    languageCode: 'en',
    countryCode: 'ZMB',
    latitude: -13.1339,
    longitude: 27.8493,
    currencyCode: 'ZMW',
  },
  {
    label: '적도기니',
    languageCode: 'es',
    countryCode: 'GNQ',
    latitude: 1.6508,
    longitude: 10.2679,
    currencyCode: 'XAF',
  },
  {
    label: '조지아',
    languageCode: 'ka',
    countryCode: 'GEO',
    latitude: 42.3154,
    longitude: 43.3569,
    currencyCode: 'GEL',
  },
  {
    label: '중국',
    languageCode: 'zh-CN',
    countryCode: 'CHN',
    latitude: 35.8617,
    longitude: 104.1954,
    currencyCode: 'CNY',
  },
  {
    label: '중앙아프리카공화국',
    languageCode: 'fr',
    countryCode: 'CAF',
    latitude: 6.6111,
    longitude: 20.9394,
    currencyCode: 'XAF',
  },
  {
    label: '지부티',
    languageCode: 'ar',
    countryCode: 'DJI',
    latitude: 11.8251,
    longitude: 42.5903,
    currencyCode: 'DJF',
  },
  {
    label: '짐바브웨',
    languageCode: 'en',
    countryCode: 'ZWE',
    latitude: -19.0154,
    longitude: 29.1549,
    currencyCode: 'ZWL',
  },
  { label: '차드', languageCode: 'fr', countryCode: 'TCD', latitude: 15.4542, longitude: 18.7322, currencyCode: 'XAF' },
  { label: '체코', languageCode: 'cs', countryCode: 'CZE', latitude: 49.8175, longitude: 15.473, currencyCode: 'CZK' },
  {
    label: '칠레',
    languageCode: 'es',
    countryCode: 'CHL',
    latitude: -35.6751,
    longitude: -71.543,
    currencyCode: 'CLP',
  },
  { label: '카메룬', languageCode: 'fr', countryCode: 'CMR', latitude: 3.848, longitude: 11.5021, currencyCode: 'XAF' },
  {
    label: '카보베르데',
    languageCode: 'pt',
    countryCode: 'CPV',
    latitude: 16.5388,
    longitude: -23.0418,
    currencyCode: 'CVE',
  },
  {
    label: '카자흐스탄',
    languageCode: 'kk',
    countryCode: 'KAZ',
    latitude: 48.0196,
    longitude: 66.9237,
    currencyCode: 'KZT',
  },
  {
    label: '카타르',
    languageCode: 'ar',
    countryCode: 'QAT',
    latitude: 25.3548,
    longitude: 51.1839,
    currencyCode: 'QAR',
  },
  {
    label: '캄보디아',
    languageCode: 'km',
    countryCode: 'KHM',
    latitude: 12.5657,
    longitude: 104.991,
    currencyCode: 'KHR',
  },
  {
    label: '캐나다',
    languageCode: 'en',
    countryCode: 'CAN',
    latitude: 56.1304,
    longitude: -106.3468,
    currencyCode: 'CAD',
  },
  { label: '케냐', languageCode: 'sw', countryCode: 'KEN', latitude: -0.0236, longitude: 37.9062, currencyCode: 'KES' },
  {
    label: '코모로',
    languageCode: 'ar',
    countryCode: 'COM',
    latitude: -11.6455,
    longitude: 43.3333,
    currencyCode: 'KMF',
  },
  {
    label: '코소보',
    languageCode: 'sq',
    countryCode: 'XKX',
    latitude: 42.6026,
    longitude: 20.903,
    currencyCode: 'EUR',
  },
  {
    label: '코스타리카',
    languageCode: 'es',
    countryCode: 'CRI',
    latitude: 9.7489,
    longitude: -83.7534,
    currencyCode: 'CRC',
  },
  {
    label: '코트디부아르',
    languageCode: 'fr',
    countryCode: 'CIV',
    latitude: 7.54,
    longitude: -5.5471,
    currencyCode: 'XOF',
  },
  {
    label: '콜롬비아',
    languageCode: 'es',
    countryCode: 'COL',
    latitude: 4.5709,
    longitude: -74.2973,
    currencyCode: 'COP',
  },
  { label: '콩고', languageCode: 'fr', countryCode: 'COG', latitude: -0.228, longitude: 15.8277, currencyCode: 'XAF' },
  {
    label: '콩고민주공화국',
    languageCode: 'fr',
    countryCode: 'COD',
    latitude: -4.0383,
    longitude: 21.7587,
    currencyCode: 'CDF',
  },
  {
    label: '쿠바',
    languageCode: 'es',
    countryCode: 'CUB',
    latitude: 21.5218,
    longitude: -77.7812,
    currencyCode: 'CUP',
  },
  {
    label: '쿠웨이트',
    languageCode: 'ar',
    countryCode: 'KWT',
    latitude: 29.3117,
    longitude: 47.4818,
    currencyCode: 'KWD',
  },
  {
    label: '쿡제도',
    languageCode: 'en',
    countryCode: 'COK',
    latitude: -21.2367,
    longitude: -159.7777,
    currencyCode: 'NZD',
  },
  { label: '크로아티아', languageCode: 'hr', countryCode: 'HRV', latitude: 45.1, longitude: 15.2, currencyCode: 'EUR' },
  {
    label: '키르기즈공화국',
    languageCode: 'ky',
    countryCode: 'KGZ',
    latitude: 41.2044,
    longitude: 74.7661,
    currencyCode: 'KGS',
  },
  {
    label: '키리바시',
    languageCode: 'en',
    countryCode: 'KIR',
    latitude: -3.3704,
    longitude: -168.734,
    currencyCode: 'AUD',
  },
  {
    label: '타지키스탄',
    languageCode: 'tg',
    countryCode: 'TJK',
    latitude: 38.861,
    longitude: 71.2761,
    currencyCode: 'TJS',
  },
  {
    label: '탄자니아',
    languageCode: 'sw',
    countryCode: 'TZA',
    latitude: -6.369,
    longitude: 34.8888,
    currencyCode: 'TZS',
  },
  { label: '태국', languageCode: 'th', countryCode: 'THA', latitude: 15.87, longitude: 100.9925, currencyCode: 'THB' },
  { label: '토고', languageCode: 'fr', countryCode: 'TGO', latitude: 8.6195, longitude: 0.8248, currencyCode: 'XOF' },
  {
    label: '통가',
    languageCode: 'en',
    countryCode: 'TON',
    latitude: -21.1789,
    longitude: -175.1982,
    currencyCode: 'TOP',
  },
  {
    label: '투르크메니스탄',
    languageCode: 'tk',
    countryCode: 'TKM',
    latitude: 38.9697,
    longitude: 59.5563,
    currencyCode: 'TMT',
  },
  {
    label: '투발루',
    languageCode: 'en',
    countryCode: 'TUV',
    latitude: -7.1095,
    longitude: 177.6493,
    currencyCode: 'AUD',
  },
  {
    label: '튀니지',
    languageCode: 'ar',
    countryCode: 'TUN',
    latitude: 33.8869,
    longitude: 9.5375,
    currencyCode: 'TND',
  },
  {
    label: '튀르키예',
    languageCode: 'tr',
    countryCode: 'TUR',
    latitude: 38.9637,
    longitude: 35.2433,
    currencyCode: 'TRY',
  },
  {
    label: '트리니다드토바고',
    languageCode: 'en',
    countryCode: 'TTO',
    latitude: 10.6918,
    longitude: -61.2225,
    currencyCode: 'TTD',
  },
  {
    label: '파나마',
    languageCode: 'es',
    countryCode: 'PAN',
    latitude: 8.538,
    longitude: -80.7821,
    currencyCode: 'PAB',
  },
  {
    label: '파라과이',
    languageCode: 'es',
    countryCode: 'PRY',
    latitude: -23.4425,
    longitude: -58.4438,
    currencyCode: 'PYG',
  },
  {
    label: '파키스탄',
    languageCode: 'ur',
    countryCode: 'PAK',
    latitude: 30.3753,
    longitude: 69.3451,
    currencyCode: 'PKR',
  },
  {
    label: '파푸아뉴기니',
    languageCode: 'en',
    countryCode: 'PNG',
    latitude: -6.3149,
    longitude: 143.9555,
    currencyCode: 'PGK',
  },
  {
    label: '팔라우',
    languageCode: 'en',
    countryCode: 'PLW',
    latitude: 7.515,
    longitude: 134.5825,
    currencyCode: 'USD',
  },
  {
    label: '팔레스타인',
    languageCode: 'ar',
    countryCode: 'PSE',
    latitude: 31.9522,
    longitude: 35.2332,
    currencyCode: 'ILS',
  },
  { label: '페루', languageCode: 'es', countryCode: 'PER', latitude: -9.19, longitude: -75.0152, currencyCode: 'PEN' },
  {
    label: '포르투갈',
    languageCode: 'pt-PT',
    countryCode: 'PRT',
    latitude: 39.3999,
    longitude: -8.2245,
    currencyCode: 'EUR',
  },
  {
    label: '폴란드',
    languageCode: 'pl',
    countryCode: 'POL',
    latitude: 51.9194,
    longitude: 19.1451,
    currencyCode: 'PLN',
  },
  {
    label: '프랑스',
    languageCode: 'fr',
    countryCode: 'FRA',
    latitude: 46.2276,
    longitude: 2.2137,
    currencyCode: 'EUR',
  },
  {
    label: '피지',
    languageCode: 'en',
    countryCode: 'FJI',
    latitude: -16.5782,
    longitude: 179.4144,
    currencyCode: 'FJD',
  },
  {
    label: '핀란드',
    languageCode: 'fi',
    countryCode: 'FIN',
    latitude: 61.9241,
    longitude: 25.7482,
    currencyCode: 'EUR',
  },
  {
    label: '필리핀',
    languageCode: 'tl',
    countryCode: 'PHL',
    latitude: 12.8797,
    longitude: 121.774,
    currencyCode: 'PHP',
  },
  {
    label: '헝가리',
    languageCode: 'hu',
    countryCode: 'HUN',
    latitude: 47.1625,
    longitude: 19.5033,
    currencyCode: 'HUF',
  },
  {
    label: '호주',
    languageCode: 'en-AU',
    countryCode: 'AUS',
    latitude: -25.2744,
    longitude: 133.7751,
    currencyCode: 'AUD',
  },
  {
    label: '홍콩',
    languageCode: 'zh-HK',
    countryCode: 'HKG',
    latitude: 22.3193,
    longitude: 114.1694,
    currencyCode: 'HKD',
  },
] as const;

export type Country = (typeof COUNTRIES)[number];
