import type { PlaceCategory } from '@/types/corePlace';

export const CATEGORY_COLORS: Record<PlaceCategory, string> = {
  restaurant: '#FF9721',
  cafe: '#b7ebb9',
  hotel: '#678fff',
  landmark: '#d3e7fd',
  shopping: '#ffd3e1',
  culture: '#6f53d3',
  leisure: '#FFD54F',
  nature: '#c1e6b0',
  sports: '#dff5ff',
  medical: '#ffbfbf',
  education: '#FFCC80',
  airport: '#d5d9db',
  terminal: '#B0BEC5',
  traffic: '#48c5ff',
  gas_station: '#b3eedf',
  parking: '#5f7480',
  convenience: '#84effd',
  atm: '#FFF176',
  etc: '#C0C8E0',
};

export const CATEGORY_EMOJI: Record<PlaceCategory, string> = {
  restaurant: '🍽',
  cafe: '☕',
  hotel: '🏢',
  landmark: '🏛',
  shopping: '🛍',
  culture: '🎭',
  leisure: '🎡',
  nature: '🌿',
  sports: '⚽',
  medical: '🏥',
  education: '📚',
  airport: '✈',
  terminal: '🚌',
  traffic: '🚈',
  gas_station: '⛽',
  parking: '🅿',
  convenience: '🏪',
  atm: '💳',
  etc: '📍',
};
